### ISSUE TITLE
[Question] How to access services directly?

### ISSUE THREAD

**Issue by hffmnn** [aws-samples/aws-saas-factory-dynamic-policy-generation#2]
Hi there and thanks for this example. I am learning a lot by reading the blog post and the code. 👍 

One question I still have:
How would it be possible to allow a (web-)client to access S3 directly (without going through the lambda) to e.g. download a file? Behavior should be the same: The client can only access the files of a specific tenant.

Ideas?

**Comment by ConnorKirk** [comment]
That is a good question, Christian. 

The answer is that it depends. It's possible to obtain replicate this pattern described in the blog without the lambda, but I don't think I can recommend it.

The `AssumeRoleWithWebIdentity` call can be used to  obtains AWS credentials for users who have been authenticated in a mobile or web application with a web identity provider. These credentials can interact directly with AWS services from the web client, such as S3. [AssumeRoleWithWebIdentity Documentation]

Similar to `AssumeRole` used in the blogpost, the `AssumeRoleWithWebIdentity` action can include an inline IAM policy to further constrain the scope of the credentials returned. 

The problem is, I do not think you can trust that the client has not adjusted the inline policy when making the `AssumeRoleWithWebIdentity` call. 

Using a lambda function (or other execution environment trusted by you) ensures that the inline policy provided is appropriate. I cannot think of a way to ensure this in a web client.

For specially working with S3 objects, presigned keys may be a better approach. These would still need to be generated by something other than the webclient however.

I hope this has answered your question. If I have missed something, please say so 🙂

[AssumeRoleWithWebIdentity Documentation]: https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html
[STS AssumeRoleWIthWebIdentity]: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_request.html#api_assumerolewithwebidentity

**Comment by hffmnn** [comment]
Hi Connor, 

thanks a lot for your answer. That answers pretty much everything I wanted to know.
To sum it up: If a user wants to access e.g. images of a specific tenant, you would add an API that returns the presigned image URLs. These can then be accessed by the user.

One more question I would have (Premature optimization, but I am interested): 
Given I would have a lot of users: How would you cache something like that? Every request to the presign API would return another set of image URLs so every user would access the images with another URL, right? Or would you generate a set of resigned URLs and return these same URLs to the user? Still, every image request would hit S3 directly.
